"""Test 2

Revision ID: b025e3dcc4af
Revises: 6e30c273f0b0
Create Date: 2023-03-07 14:15:39.736159

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'b025e3dcc4af'
down_revision = '6e30c273f0b0'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('themes', sa.Column('easy_words_id', sa.Integer(), nullable=True))
    op.add_column('themes', sa.Column('medium_words_id', sa.Integer(), nullable=True))
    op.add_column('themes', sa.Column('difficult_words_id', sa.Integer(), nullable=True))
    op.drop_constraint(None, 'themes', type_='foreignkey')
    op.create_foreign_key(None, 'themes', 'medium', ['medium_words_id'], ['id'])
    op.create_foreign_key(None, 'themes', 'easy', ['easy_words_id'], ['id'])
    op.create_foreign_key(None, 'themes', 'difficult', ['difficult_words_id'], ['id'])
    op.drop_column('themes', 'words_id')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('themes', sa.Column('words_id', sa.INTEGER(), nullable=True))
    op.drop_constraint(None, 'themes', type_='foreignkey')
    op.drop_constraint(None, 'themes', type_='foreignkey')
    op.drop_constraint(None, 'themes', type_='foreignkey')
    op.create_foreign_key(None, 'themes', 'easy', ['words_id'], ['id'])
    op.drop_column('themes', 'difficult_words_id')
    op.drop_column('themes', 'medium_words_id')
    op.drop_column('themes', 'easy_words_id')
    # ### end Alembic commands ###
